name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Rust Toolchains
        uses: actions/cache@v2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/work/_temp/_github_home/.rustup/toolchains
            ~/work/_temp/_github_home/.rustup/update-hashes

      - name: Cache Cargo and Rust Build
        uses: actions/cache@v2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/work/_temp/_github_home/.cargo/registry
            ~/work/_temp/_github_home/.cargo/git
            target
          key: ${{ github.job }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ hashFiles('rust-toolchain') }}-

      - name: Build
        uses: ./ci/github-actions/arch-run
        with:
          command: cargo build --locked

      - name: Test
        uses: ./ci/github-actions/arch-run
        with:
          command: cargo test

      - name: Enable reading of cache
        continue-on-error: true
        uses: ./ci/github-actions/arch-run
        with:
          command: chmod -R a+rwX $HOME/.cargo target

  clippy_check:
    name: Clippy

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Cargo and Rust Build
        uses: actions/cache@v2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.job }}-${{ matrix.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ matrix.os }}-${{ hashFiles('rust-toolchain') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ matrix.os }}-${{ hashFiles('rust-toolchain') }}-

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          components: clippy
          override: 'true'
          default: 'true'

      - name: Use clippy to lint code
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Report (${{ hashFiles('rust-toolchain') }}, ${{ matrix.os }})
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

  fmt_check:
    name: Fmt

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          components: rustfmt
          override: 'true'
          default: 'true'

      - name: Check code formatting
        run: cargo fmt -- --check
